version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/discord_bot.py
    env_file:
      - .env
    volumes:
      - .:/app

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/telegram_bot.py
    env_file:
      - .env
    volumes:
      - .:/app

  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/notifier.py
    env_file:
      - .env
    volumes:
      - .:/app

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/scheduler.py
    env_file:
      - .env
    volumes:
      - .:/app

  websocket_feed:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/websocket_feed.py
    env_file:
      - .env
    volumes:
      - .:/app
