name: Deploy Static Site to S3/CloudFront

on:
  push:
    branches: [main]
    paths: ['client/**']
  workflow_dispatch:

env:
  BUCKET_NAME: genx-fx-static-9319
  DISTRIBUTION_ID: E3SP3XU9YMK917
  CLOUDFRONT_URL: https://dfdc34s1qr7cw.cloudfront.net
  S3_WEBSITE_URL: https://genx-fx-static-9319.s3-website-us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build client application
      run: |
        if [ -d "client" ]; then
          cd client
          if [ -f "package.json" ]; then
            npm install
            npm run build
            echo "Build completed"
          else
            echo "No build process needed, using static files as-is"
          fi
          cd ..
        fi

    - name: Deploy to S3
      run: |
        echo "📤 Uploading files to S3 bucket: $BUCKET_NAME"
        aws s3 sync client/ s3://$BUCKET_NAME/ --delete --region us-east-1

    - name: Invalidate CloudFront
      run: |
        echo "🔄 Invalidating CloudFront cache..."
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --region us-east-1

    - name: Get CloudFront status
      run: |
        echo "📊 CloudFront distribution status:"
        aws cloudfront get-distribution --id $DISTRIBUTION_ID --query "Distribution.{Status:Status,DomainName:DomainName}" --region us-east-1

    - name: Deployment Summary
      run: |
        echo "✅ Static site deployment completed!"
        echo ""
        echo "🌐 Your site is available at:"
        echo "   CloudFront (HTTPS): $CLOUDFRONT_URL"
        echo "   S3 Website (HTTP):  $S3_WEBSITE_URL"
        echo ""
        echo "🔗 CloudFront URL: $CLOUDFRONT_URL"
