name: Run Tests and Quality Checks
on: 
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    name: Python Tests & Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx pybit pytest-mock
          
      - name: Run tests
        run: |
          python -m pytest tests/test_basic.py -v --tb=short
          
      - name: Run basic linting
        run: |
          echo "Running basic linting checks..."
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          
      - name: Test Docker build
        run: |
          echo "Testing Docker build..."
          docker build -t genx-fx-test . || true
          echo "Docker build test completed"